# 站点的基本信息，会被模板和 SEO 插件使用
title: Tung Website   # 网站标题
author: Tung Chia-hui # 作者名，可以在文章或页面引用
email: tungchiahui@gmail.com # 作者邮箱，可选，主要用于 feed 或 SEO
description: >-  # 网站描述，用于 meta 标签和搜索引擎
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# 网站的根路径配置
baseurl: "" # 子路径，如果你的网站不是放在根目录，比如 /blog，就填 "/blog"；放在根域名上就留空
url: "https://me.tungchiahui.cn" # 网站主域名，建议写完整带 https:// 的，比如 "https://tungchiahui.cn"

# ICP 与公安备案号（自定义字段）
icp: "鲁ICP备2025185601号-2"       # 工信部备案号
beian: "xxxxxxxxxxxxxx"            # 公安备案号
# 自定义变量，可以在 footer.html 中用 {{ site.icp }} 和 {{ site.beian }} 调用

# 社交/联系方式配置(没有就注释掉或者删掉这一项就行)
social:
  email: "mailto:tungchiahui@gmail.com"
  website: "https://me.tungchiahui.cn"
  github: "https://github.com/tungchiahui"
  qq: "https://qm.qq.com/q/JRhksaNK82?from=qq"
  telegram: "https://t.me/tungchiahui"
  bilibili: "https://space.bilibili.com/141482453"
  coolapk: "http://www.coolapk.com/u/3224578"
  twitter: "https://twitter.com/tungchiahui"
  youtube: "https://www.youtube.com/@Chia-huiTung"
  facebook: "https://www.facebook.com/tungchiahui"
  instagram: "https://www.instagram.com/tungchiahui"



# 构建相关配置
# theme: tung_theme # 主题，这里被注释掉了，说明你可能用了自己写的布局而不是 gem-based 主题

plugins:
  - jekyll-feed      # 自动生成 RSS feed（/feed.xml），可选，博客用得多
  - jekyll-seo-tag   # 自动生成 SEO 相关的 meta 标签，推荐开启

# 自定义集合配置（这里定义了 _pages 文件夹）
collections:
  pages:
    output: true        # 表示这些页面会生成静态文件
    permalink: /:path/  # URL 规则，比如 _pages/about.md 会变成 /about/

# 启动代码高亮,Markdown相关配置
markdown: kramdown
highlighter: rouge

# 代码高亮配置，启用行号
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true  # 全局启用行号
