import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import OpenCC from 'opencc-js'
import { pageCopySource } from '../utils/i18n-page-copy-source'

type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue }

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outputFile = path.join(rootDir, 'utils/generated/i18n-page-copy.ts')

const converters = {
  'zh-hant': OpenCC.Converter({ from: 'cn', to: 't' }),
  'zh-hk': OpenCC.Converter({ from: 'cn', to: 'hk' }),
  'zh-tw': OpenCC.Converter({ from: 'cn', to: 'tw' })
} as const

const generated = Object.fromEntries(
  Object.entries(pageCopySource).map(([page, copy]) => [
    page,
    {
      'zh-cn': copy.zh,
      'zh-hant': convertValue(copy.zh, converters['zh-hant']),
      'zh-hk': convertValue(copy.zh, converters['zh-hk']),
      'zh-tw': convertValue(copy.zh, converters['zh-tw']),
      'en-us': copy.en
    }
  ])
)

await fs.mkdir(path.dirname(outputFile), { recursive: true })
await fs.writeFile(
  outputFile,
  [
    '// This file is generated by scripts/i18n-generate-ui.ts. Do not edit it by hand.',
    '',
    `export const pageCopy = ${JSON.stringify(generated, null, 2)} as const`,
    '',
    'export type PageCopy = typeof pageCopy',
    'export type PageCopyName = keyof PageCopy',
    ''
  ].join('\n')
)

console.log(`i18n-ui: generated ${path.relative(rootDir, outputFile)}`)

function convertValue<T extends JsonValue>(value: T, converter: (input: string) => string): T {
  if (typeof value === 'string') return converter(value) as T
  if (Array.isArray(value)) return value.map(item => convertValue(item, converter)) as T
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, convertValue(item, converter)])
    ) as T
  }
  return value
}
