import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createHash } from 'node:crypto'
import OpenCC from 'opencc-js'
import { pageCopySource } from '../utils/i18n-page-copy-source'

type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue }
type PageCopyEntry = {
  zh: JsonValue
  en?: JsonValue
}
type MemoryEntry = {
  source: string
  target: string
}
type MemoryStore = Record<string, MemoryEntry>

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outputFile = path.join(rootDir, 'utils/generated/i18n-page-copy.ts')
const memoryFile = path.join(rootDir, 'i18n/ui-memory/en-us.json')

const converters = {
  'zh-hant': OpenCC.Converter({ from: 'cn', to: 't' }),
  'zh-hk': OpenCC.Converter({ from: 'cn', to: 'hk' }),
  'zh-tw': OpenCC.Converter({ from: 'cn', to: 'tw' })
} as const

const memory = await readJson<MemoryStore>(memoryFile, {})

const generated = Object.fromEntries(
  Object.entries(pageCopySource as Record<string, PageCopyEntry>).map(([page, copy]) => [
    page,
    {
      'zh-cn': copy.zh,
      'zh-hant': convertValue(copy.zh, converters['zh-hant']),
      'zh-hk': convertValue(copy.zh, converters['zh-hk']),
      'zh-tw': convertValue(copy.zh, converters['zh-tw']),
      'en-us': localizeEnglish(page, copy.zh, memory, copy.en)
    }
  ])
)

await fs.mkdir(path.dirname(outputFile), { recursive: true })
await fs.writeFile(
  outputFile,
  [
    '// This file is generated by scripts/i18n-generate-ui.ts. Do not edit it by hand.',
    '',
    `export const pageCopy = ${JSON.stringify(generated, null, 2)} as const`,
    '',
    'export type PageCopy = typeof pageCopy',
    'export type PageCopyName = keyof PageCopy',
    ''
  ].join('\n')
)

console.log(`i18n-ui: generated ${path.relative(rootDir, outputFile)}`)

function convertValue<T extends JsonValue>(value: T, converter: (input: string) => string): T {
  if (typeof value === 'string') return converter(value) as T
  if (Array.isArray(value)) return value.map(item => convertValue(item, converter)) as T
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, convertValue(item, converter)])
    ) as T
  }
  return value
}

function localizeEnglish<T extends JsonValue>(page: string, value: T, memory: MemoryStore, fallback?: JsonValue, keyPath: string[] = []): T {
  if (typeof value === 'string') {
    const fallbackText = typeof fallback === 'string' ? fallback : value
    if (!containsChinese(value)) return fallbackText as T

    const pathKey = [page, ...keyPath].join('.')
    return (memory[memoryKey(pathKey, value)]?.target || fallbackText) as T
  }

  if (Array.isArray(value)) {
    const fallbackItems = Array.isArray(fallback) ? fallback : []
    return value.map((item, index) => localizeEnglish(page, item, memory, fallbackItems[index], [...keyPath, String(index)])) as T
  }

  if (value && typeof value === 'object') {
    const fallbackObject = fallback && typeof fallback === 'object' && !Array.isArray(fallback) ? fallback as Record<string, JsonValue> : {}
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, localizeEnglish(page, item, memory, fallbackObject[key], [...keyPath, key])])
    ) as T
  }

  return value
}

async function readJson<T>(file: string, fallback: T): Promise<T> {
  try {
    return JSON.parse(await fs.readFile(file, 'utf8')) as T
  } catch {
    return fallback
  }
}

function memoryKey(pathKey: string, source: string) {
  return `${pathKey}:${hashText(source)}`
}

function hashText(value: string) {
  return createHash('sha256').update(value.replace(/\s+/g, ' ').trim()).digest('hex')
}

function containsChinese(value: string) {
  return /[\u3400-\u9fff]/.test(value)
}
